### ISSUE TITLE
prototype sort code crashes on trying to print output

### ISSUE THREAD

**Issue by jeftreece** [jazdrv/dnaTools#27]
Reproduce: 
set kitlimit to 50 in config.yaml, drop tables
redux.py -t
redux.py -o
redux.py -mp
redux.py -m

observe error:
Beginning run [00:49:07]
beg MatrixData restore: 0.99071
end MatrixData restore: 1.002341
beg stdout-matrix: 1.00277

Traceback (most recent call last):
  File "./redux.py", line 198, in <module>
    vt.matrix(args.rest)
  File "./sort.py", line 134, in matrix
    self.sort.stdout_matrix(vix=vix,kix=kix)
  File "./sort.py", line 1456, in stdout_matrix
    print(table)
  File "/u/treece/.local/lib/python3.6/site-packages/beautifultable/beautifultable.py", line 498, in __str__
    return self.get_string()
  File "/u/treece/.local/lib/python3.6/site-packages/beautifultable/beautifultable.py", line 1071, in get_string
    content = str(row)
  File "/u/treece/.local/lib/python3.6/site-packages/beautifultable/rows.py", line 103, in __str__
    row[i] = '{:{sign}}'.format(row[i], sign=sign.value)
TypeError: unsupported format string passed to NoneType.__format__

**Comment by jazdrv** [comment]
you're running 50 kits?

I've only been doing 16. That's all I can get my hands on.

I haven't stress tested beautifultable with lots of data; I wasn't sure it would be something that could carry a big load like the project will need in its full scope. As I saw it, it was something so I could visually work out bugs and such with smaller sets of data. But sure if the idea continued to work with larger sets of data in a practical way ... then that would be great too.

Stuff like this ... I would need to be working with a similar data construct you are to be at all helpful. Because I can't recreate your error otherwise.

Zak

**Comment by jeftreece** [comment]
I have seen this with different number of kits, and it does not require 50 kits to reproduce. However, I agree it's input dependent. I'll narrow it down to a smaller repro, but as I noted in a separate thread, if row[i] is None, it's easy to reproduce outside of bt
